apiVersion: v1
kind: Service
metadata:
  name: starwars-api-kotlin
  labels:
    app: starwars-api-kotlin
spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
        app: starwars-api-kotlin