spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      database: starwars
      password: password
      authSource: admin
  webflux:
    base-path: /

kafka:
  bootstrap:
    address: 'http://localhost:9092'

clients:
  starwars:
    name: starwars
    url: http://localhost:9999/starwars-api